### ISSUE TITLE
Loading crash

### ISSUE THREAD

**Issue by Rei366** [GoldRenard/DMOAdvancedLauncher#75]
The launcher crashes every time after reaching the "HOSTNAME VALIDATION LOADING..." phase right before it can actually show itself. (I only see the little "loading window" then it crashes)

**Comment by GoldRenard** [comment]
It would be great if you will submit BugTrap crash report. It will be automatically uploaded to my server with all necessary information about crash.

![vshgldq](https://cloud.githubusercontent.com/assets/6066246/11424493/b58d4bf6-945e-11e5-9943-44a28fbbfcfa.png)

**Comment by GoldRenard** [comment]
BugTrap should appear right after crash. If it doesn't, let me know.

**Comment by GoldRenard** [comment]
Fixed. https://github.com/GoldRenard/DMOAdvancedLauncher/commit/928ab74471fbdee67e7ca3d7f4f4f255f322a3a7
