### ISSUE TITLE
The launcher stop downloading in the last %

### ISSUE THREAD

**Issue by articzapmol** [GoldRenard/DMOAdvancedLauncher#76]
i've been triying to download the launcher like 20 times now and it just stop at the last 99%

i tried downloading the open sources and they were fine but i dont know what to do with them

**Comment by GoldRenard** [comment]
Hello. Looks like connection issues or smth on your side. Try to download it from [AppVeyor](https://ci.appveyor.com/project/GoldRenard/dmoadvancedlauncher/build/3.2.140/artifacts). If it doesn’t work, try with another browser / download manager.

**Comment by articzapmol** [comment]
Got to download the program I really appreciate it

Enviado desde Outlook




On Mon, Nov 30, 2015 at 4:35 AM -0800, "Renard Gold" <notifications@github.com> wrote:





Closed #76.

---
Reply to this email directly or view it on GitHub:
https://github.com/GoldRenard/DMOAdvancedLauncher/issues/76#event-477661467
